### ISSUE TITLE
Get HDF5 TAQ files from Xin Guo

### ISSUE THREAD

**Issue by davclark** [berkeley-dsc/dlab-finance#10]
He's got a website here: http://ieor.berkeley.edu/~xinguo/

Though we may want to experiment with making our own...

**Comment by rdhyee** [comment]
In my conversations with Krisha last week, he mentioned a prof who has HDF5 versions of TAQ files.  I think I may have actually been on a phone call once with Xin Guo (http://www.ieor.berkeley.edu/People/Faculty/xinguo.htm) -- small world.

**Comment by davclark** [comment]
Yes - this is the prof that Krishna knows about. I just put this on the
back-burner, as it will only give us one approach to storing the data (and
pytables or other database approaches to indexing will be far more flexible
than the more hierarchical approach Xin Guo used).

On Mon, Jul 13, 2015 at 10:58 PM, Raymond Yee <notifications@github.com>
wrote:

> In my conversations with Krisha last week, he mentioned a prof who has
> HDF5 versions of TAQ files. I think I may have actually been on a phone
> call once with Xin Guo (
> http://www.ieor.berkeley.edu/People/Faculty/xinguo.htm) -- small world.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/berkeley-dsc/dlab-finance/issues/10#issuecomment-121139206>
> .
>



-- 
Dav Clark
Data Scientist
Berkeley D-Lab + BIDS
bead.glass
917-544-8408
