### ISSUE TITLE
Run summary stats job on SAVIO

### ISSUE THREAD

**Issue by davclark** [berkeley-dsc/dlab-finance#18]
See here for general details:

http://research-it.berkeley.edu/services/high-performance-computing/slurm-usage-instructions

We are account co_dlab, use qos dlab_normal

**Comment by Jay4869** [comment]
I have review this link you provide, but it does not tell how to include the python file, and submit the .sh file on the SAVIO?

**Comment by Jay4869** [comment]
Hi, Dav
Under Jack's help, I did transfer the all files to the SAVIO, and try to run them. Now, I got error is SAVIO python does not have pytz so that I cannot run raw_tag.py

**Comment by Jay4869** [comment]
error is showing below
[jli4869@ln000 nbbo]$ python SAVIO_run.py
Traceback (most recent call last):
  File "SAVIO_run.py", line 2, in <module>
    import raw_taq
  File "/global/home/users/jli4869/work/dlab-finance/nbbo/raw_taq.py", line 4, in <module>
    from pytz import timezone
ImportError: No module named pytz

**Comment by davclark** [comment]
This is probably because of your using the standard system python, which is old and has few libraries we need. I just install and use miniconda (py3 version) from [here](http://conda.pydata.org/miniconda.html). However, it's already downloaded in my user directory on Savio, in `~dav/archive`. So, you can run the installer from there.

**Comment by davclark** [comment]
Note that you'll need to actually source your bash config to get things set up right - the easiest way to check is to log out, then back in, and see if you get something like the following:

```
$ which python
~/miniconda3/bin/python
```

**Comment by Jay4869** [comment]
Thank you sharing the resource to me! I will work on this. If I have
further questions, we will meet tomorrow. You help me a lot :)

Best

2015-06-22 15:36 GMT-07:00 Dav Clark <notifications@github.com>:

**Comment by davclark** [comment]
Oh - also, once that's set up, you'll need to install the relevant packages... something like: `conda install pytables numpy pytz`.

**Comment by Jay4869** [comment]
So, basically miniconda3 is a python package and I can install modules
from miniconda3
on the SAVIO such as pytables, numpy. pytz?

2015-06-22 15:53 GMT-07:00 Dav Clark <notifications@github.com>:

**Comment by davclark** [comment]
Miniconda is more a python "environment" - comparable to enthought canopy, but command-line only. It is a stripped-down version of [Continuum Anaconda](https://store.continuum.io/cshop/anaconda/).
