### ISSUE TITLE
Bug on running the stat summary on 20150102

### ISSUE THREAD

**Issue by Jay4869** [berkeley-dsc/dlab-finance#24]
I am running the python file on 20140206, which is fine. However, when I run the same code on 20150102 occurs the error about StatisticsError. Could you please run once to check whether you also have error? Following is what I got feedback

Current symbol: b'A     ' 6 records
Max bid price:  41.0
 Min bid price:  0.0
 Mean bid price:  28.2145
 Mod bid price:  37.13
 Standard deviation bid price:  16.3251399611
Current symbol: b'AA    ' 6 records
Max bid price:  15.79
 Min bid price:  0.0
 Mean bid price:  13.7088235294
 Mod bid price:  15.61
 Standard deviation bid price:  5.01430410673
Current symbol: b'AAC   ' 6 records
Max bid price:  30.46
 Min bid price:  0.0
 Mean bid price:  20.3066666667
 Mod bid price:  30.46
 Standard deviation bid price:  14.3589817033
Current symbol: b'AADR  ' 6 records
Traceback (most recent call last):
  File "run.py", line 21, in print_stats
    mod_price = mode(chunk['Bid_Price'])
  File "/global/home/users/jli4869/miniconda3/lib/python3.4/statistics.py", line
 434, in mode
    'no unique mode; found %d equally common values' % len(table)
statistics.StatisticsError: no unique mode; found 3 equally common values

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 54, in <module>
    print_stats(accum)
  File "run.py", line 22, in print_stats
    except StatisticsError:
NameError: name 'StatisticsError' is not defined

@davclark

**Comment by davclark** [comment]
Oops! That exception needs to be imported from the statistics package!

Have you read about how exceptions work in python?

**Comment by Jay4869** [comment]
Thanks, Dav.
I believe I fix it, but now, I cannot connect to the SAVIO. Once I can login, I will run and check how it works
