### ISSUE TITLE
Run jobs in parallel and do benchmarks

### ISSUE THREAD

**Issue by davclark** [berkeley-dsc/dlab-finance#25]
Get an example of how to structure this from:
```
pynbbo_sample.sbatch
pynbbo_sample.taskfile
```

Then get a sense of timing based on logfiles, and perhaps using `time` (see `man time`).

**Comment by davclark** [comment]
Ideally, have the raw timing saved to a CSV or similar, and also generate a graph (probably using [matplotlib](http://matplotlib.org/users/pyplot_tutorial.html)).

You can generate the raw data on Savio, but do plotting on your own computer (interactivity / GUI is nice for this!).

**Comment by davclark** [comment]
See #13 for some examples!

**Comment by Jay4869** [comment]
I have a question about this task
You want me to figure out the best combination to run one file "20150102" in the shortest time, not the whole BBO files?

**Comment by davclark** [comment]
The idea is to run jobs in parallel to see how much we can do at once.
E.g., you might see that 7 files are about as far as 1, but 8 files take
much longer than 7.

I don't think you'll be able to speed a single file up much, but you can
try.

**Comment by Jay4869** [comment]
Hi Dav
I have figured out the parallel computation task, and I got the best point is running 10 files at once, which is the most efficient. By the way, each month data from BBO contains twenty records, so we only need to run two times for each month.
And also, Raymond asks me to analyze what attributes are the most meaningful to us doing further analysis so that we don't have to convert the entire dataset, which save a lot of time.
  
![parallel time](https://cloud.githubusercontent.com/assets/8618777/8485778/2367b210-20b5-11e5-8454-3d29476b75f3.png)

**Comment by davclark** [comment]
Interesting... that is a very strange result, I wouldn't expect such a
sharp discontinuity. Is your code for this checked in to github?

cc: @rdhyee

On Thu, Jul 2, 2015 at 12:29 PM, JIE LI <notifications@github.com> wrote:

> Hi Dav
> I have figured out the parallel computation task, and I got the best point
> is running 10 files at once, which is the most efficient. By the way, each
> month data from BBO contains twenty records, so we only need to run two
> times for each month.
> And also, Raymond asks me to analyze what attributes are the most
> meaningful to us doing further analysis so that we don't have to convert
> the entire dataset, which save a lot of time.
>
> [image: parallel time]
> <https://cloud.githubusercontent.com/assets/8618777/8485778/2367b210-20b5-11e5-8454-3d29476b75f3.png>
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/berkeley-dsc/dlab-finance/issues/25#issuecomment-118140841>
> .
>



-- 
Dav Clark
Data Scientist
Berkeley D-Lab + BIDS
bead.glass
917-544-8408

**Comment by Jay4869** [comment]
I have already commit all files on the github, and it is also surprised to me, so I redo the parallel (10 files) three times. I got two times only runing 60 seconds, but one time spent 388 seconds. These are interesting.

**Comment by Jay4869** [comment]
Following is what I got from .out file
```
[jli4869@ln000 basic-taq]$ cat slurm-407237.out
Jul 02 14:50:12 INFO: Proceed with 8 parallel task(s) and 1 processor(s) per tas
k on 10 task(s) and a 8-processor allocation.
Jul 02 14:50:12 INFO: Starting task 0 from taq_htc.407237.taskfile.0 on taq_htc.
407237.hostfile.0 at Thu Jul 2 14:50:12 PDT 2015.
Jul 02 14:50:12 INFO: Starting task 1 from taq_htc.407237.taskfile.1 on taq_htc.
407237.hostfile.1 at Thu Jul 2 14:50:12 PDT 2015.
Jul 02 14:50:12 INFO: Starting task 2 from taq_htc.407237.taskfile.2 on taq_htc.
407237.hostfile.2 at Thu Jul 2 14:50:12 PDT 2015.
Jul 02 14:50:12 INFO: Starting task 3 from taq_htc.407237.taskfile.3 on taq_htc.
407237.hostfile.3 at Thu Jul 2 14:50:12 PDT 2015.
Jul 02 14:50:12 INFO: Starting task 4 from taq_htc.407237.taskfile.4 on taq_htc.
407237.hostfile.4 at Thu Jul 2 14:50:12 PDT 2015.
Jul 02 14:50:12 INFO: Starting task 5 from taq_htc.407237.taskfile.5 on taq_htc.
407237.hostfile.5 at Thu Jul 2 14:50:12 PDT 2015.
Jul 02 14:50:12 INFO: Starting task 6 from taq_htc.407237.taskfile.6 on taq_htc.
407237.hostfile.6 at Thu Jul 2 14:50:12 PDT 2015.
Jul 02 14:50:12 INFO: Starting task 7 from taq_htc.407237.taskfile.7 on taq_htc.
407237.hostfile.7 at Thu Jul 2 14:50:12 PDT 2015.
Jul 02 14:51:12 INFO: Starting task 8 from taq_htc.407237.taskfile.8 on taq_htc.
407237.hostfile.0 at Thu Jul 2 14:51:12 PDT 2015.
Jul 02 14:51:12 INFO: Starting task 9 from taq_htc.407237.taskfile.9 on taq_htc.
407237.hostfile.1 at Thu Jul 2 14:51:12 PDT 2015.
Jul 02 14:51:12 INFO: Starting task 10 from taq_htc.407237.taskfile.10 on taq_ht
c.407237.hostfile.2 at Thu Jul 2 14:51:12 PDT 2015.
Jul 02 14:51:12 INFO: Starting task 11 from taq_htc.407237.taskfile.11 on taq_ht
c.407237.hostfile.3 at Thu Jul 2 14:51:12 PDT 2015.
Jul 02 14:51:12 INFO: Starting task 12 from taq_htc.407237.taskfile.12 on taq_ht
c.407237.hostfile.4 at Thu Jul 2 14:51:12 PDT 2015.
Jul 02 14:51:12 INFO: Starting task 13 from taq_htc.407237.taskfile.13 on taq_ht
c.407237.hostfile.5 at Thu Jul 2 14:51:12 PDT 2015.
Jul 02 14:51:12 INFO: Starting task 14 from taq_htc.407237.taskfile.14 on taq_ht
c.407237.hostfile.6 at Thu Jul 2 14:51:12 PDT 2015.
Jul 02 14:51:12 INFO: Starting task 15 from taq_htc.407237.taskfile.15 on taq_ht
c.407237.hostfile.7 at Thu Jul 2 14:51:12 PDT 2015.
Jul 02 14:52:12 INFO: 8 parallel task(s) and 1 processor(s) per task on 10 task(
s) and a 8-processor allocation have been successfully completed.
```

**Comment by Jay4869** [comment]
I have some bugs here, and I try to fix and post the result here

**Comment by Jay4869** [comment]
Hi, Dav
I fix some mistakes, and now I got the result like following
![figure_1](https://cloud.githubusercontent.com/assets/8618777/8512683/38d7c77a-2303-11e5-92af-324adac6f459.png)
