### ISSUE TITLE
Missing column in the latest dataset 

### ISSUE THREAD

**Issue by Jay4869** [berkeley-dsc/dlab-finance#27]
I am comparing the latest dataset, and found it is missing the last seven columns, so do we need to fix the raw_taq files in order to convert to .h5 correctly? 
```
                 ('Retail_Interest_Indicator_RPI', 'S1'),
                 ('Short_Sale_Restriction_Indicator', 'S1'),
                 ('LULD_BBO_Indicator_CQS', 'S1'),
                 ('LULD_BBO_Indicator_UTP', 'S1'),
                 ('FINRA_ADF_MPID_Indicator', 'S1'),
                 ('SIP_generated_Message_Identifier', 'S1'),
                 ('National_BBO_LULD_Indicator', 'S1')
```
![image](https://cloud.githubusercontent.com/assets/8618777/8509085/41ea926c-2244-11e5-8677-00d93d9c46f0.png)

**Comment by rdhyee** [comment]
@Jay4869 which dataset exactly are you looking at?   https://gist.github.com/rdhyee/8df73052c7aba1e2d89d is a list of bbo files with the width of the records.  If the dataset is a recent one, I'd expect all the columns to be present.  One thing to note:  the columns might be just spaces.

**Comment by Jay4869** [comment]
I am looking at 20150102, the last time, you said there are some bytes missing, so I found the exactly missing columns

**Comment by davclark** [comment]
Are you sure you're clear on columns vs. data in the columns? The screenshots look correct (and it looks like some of the fields are simply empty - consisting of a space).

**Comment by Jay4869** [comment]
@davclark I just found what exactly columns missing in the data (20150102) vs. the older data
Last week, we discussed that the old data has 98 bytes, but the latest data only has 89 bytes. When I was reviewing all the attributes, I just post them.

**Comment by rdhyee** [comment]
@Jay4869 You might think there are only 89 characters, but there are actually 98.  I used zless and head to extract the first 10 lines to 

~ryee/EQY_US_ALL_BBO_20150102.zip.head

via

zless EQY_US_ALL_BBO_20150102.zip | head > ~ryee/EQY_US_ALL_BBO_20150102.zip.head

If you look at ~ryee/EQY_US_ALL_BBO_20150102.zip.head, you'll see blank columns in line 2 and beyond....use a text editor like vi or write a short python script to convince yourself.  

(The thing I just learned is that the header line is actually the same width as the other lines too...)

**Comment by Jay4869** [comment]
sublime tells it has 90 columns @rdhyee 
![image](https://cloud.githubusercontent.com/assets/8618777/8513803/12ca50ea-232e-11e5-9f14-e706cbbb53ee.png)

**Comment by davclark** [comment]
My suspicion is that you can still move your cursor to the right into some
blank space. We may need to sit down together to clear this up.

**Comment by rdhyee** [comment]
@Jay4869 and I are scheduled to meet tomorrow to talk...hopefully, we can get this issue squared away then.
