### ISSUE TITLE
debug in the raw_taq_new

### ISSUE THREAD

**Issue by Jay4869** [berkeley-dsc/dlab-finance#31]
I have a question about raw_taq_new code which Dav edited on Monday. There is a parameter (dtype) that I am not very clear what we are supposed to pass in those two function.
```
def convert_taq(self):
      all_strings = np.ndarray(len(raw_bytes) // bytes_per_line,
                                                     buffer=raw_bytes,
                                                     dtype=bytes_spec.dtype)

def chunks(elf, numlines, infile, chunksize=None):
     all_strings = np.ndarray(chunksize, buffer=raw_bytes, dtype=bytes_spec.dtype)
```
the error: bytes_spec has no attributes dtype. And I checked original code, we should pass into two different things, could you take your time to look up this one?

**Comment by davclark** [comment]
I had a look. No promises that things are working, but I tried to clear things up (and implement logic that was missing).

**Comment by Jay4869** [comment]
will you have time on tomorrow? Maybe about 30 mins, we can work together. Or I check your google calendar and make the schedule?

**Comment by davclark** [comment]
Sure, put something on my Calendar.
