### ISSUE TITLE
bashrc file - listing likely modules

### ISSUE THREAD

**Issue by nitalpatwa** [berkeley-dsc/dlab-finance#4]
module load python/2.7.8
module load scikit-learn

module load matplotlib
module load pandas
module load ipython
module load jinja2
module load pyzmq
module load tornado

tradedata="/global/scratch/aculich/mirror/EQY_US_ALL_TRADE"
quotedata="/global/scratch/aculich/mirror/EQY_US_ALL_BBO"

**Comment by davclark** [comment]
I committed a slightly modified version of this [here](https://github.com/berkeley-dsc/dlab-finance/blob/master/example-bashrc).
