### ISSUE TITLE
Git issue

### ISSUE THREAD

**Issue by rsoni1** [berkeley-dsc/dlab-finance#6]
Team,

I am finally able to parse and count the TAQ data... the format pdf helped. I am however unable to check in my code from Savio.

git operations work fine from my local machine but I am getting this error when I try to push from Savio
git push
error: The requested URL returned error: 403 Forbidden while accessing https://github.com/berkeley-dsc/dlab-finance/info/refs

fatal: HTTP request failed

I am not a git expert but can you please point me to what might I be missing?

Thanks
Ritesh

**Comment by nitalpatwa** [comment]
Ritesh,
Great. I am behind. But how did you get around dying spark processes?

Nital Patwa

**Comment by rsoni1** [comment]
The dying threads is a very real issue and I have updated that issue with what Yon requested.

**Comment by rsoni1** [comment]
Ok resolved this by switching to using the ssh endpoint for git instead of https
